import type { CarouselFormat } from "./types";
import type { InstagramCarouselContent } from "@/lib/server/social/instagram/schemas";

/**
 * Carrosséis canned para o preview do painel — nenhuma chamada de IA. O
 * conteúdo espelha o style guide validado com o time.
 */

const CAPTION_STUB = {
  headline: "Exemplo de legenda para o preview",
  intro_summary: "Este é um texto de exemplo usado só na pré-visualização do painel de design.",
  key_takeaways: ["Ponto de exemplo 1", "Ponto de exemplo 2"],
  cta_call: "Comente a palavra do post nos comentários",
  hashtags: ["#inteligenciaartificial", "#desbuguei", "#redessociais"],
  full_caption: "Legenda completa de exemplo para a pré-visualização do painel de design do carrossel.",
};

const noticia: InstagramCarouselContent = {
  title: "Notícia — exemplo de carrossel",
  edition_date: "2026-01-01",
  primary_topic: "Inteligência Artificial",
  target_audience_focus: "Criadores, Vendedores & Empreendedores",
  format: "noticia",
  caption: CAPTION_STUB,
  slides: [
    {
      index: 1,
      type: "cover",
      eyebrow: "",
      title: "OpenAI libera modo agente no ChatGPT pra todo mundo",
      body: "",
      bullet_points: [],
      highlight_text: "",
      variant: "",
      cover_variant: "dark_speaker",
      headline_style: "clean",
      cover_image_prompt: "",
      bg_image_url: "",
      cta_text: "",
    },
  ],
};

const tutorial: InstagramCarouselContent = {
  title: "Tutorial — exemplo de carrossel",
  edition_date: "2026-01-01",
  primary_topic: "Claude Code",
  target_audience_focus: "Criadores, Vendedores & Empreendedores",
  format: "tutorial",
  caption: CAPTION_STUB,
  slides: [
    {
      index: 1,
      type: "cover",
      eyebrow: "6 PASSOS · 4 MIN",
      title: "Rodando seu primeiro agente no Claude Code",
      body: "",
      bullet_points: [],
      highlight_text: "",
      variant: "",
      cover_variant: "dark_speaker",
      headline_style: "clean",
      cover_image_prompt: "",
      bg_image_url: "",
      cta_text: "",
    },
    {
      index: 2,
      type: "step",
      eyebrow: "PASSO 01 DE 04",
      title: "Instale a CLI",
      body: "Um comando. Funciona em Mac, Linux e Windows via WSL.",
      bullet_points: ["$ npm install -g @anthropic-ai/claude-code"],
      highlight_text: "",
      variant: "",
      cover_variant: "dark_speaker",
      headline_style: "clean",
      cover_image_prompt: "",
      bg_image_url: "",
      cta_text: "",
    },
    {
      index: 3,
      type: "step",
      eyebrow: "PASSO 02 DE 04",
      title: "Crie o arquivo do agente",
      body: "",
      bullet_points: ["# .claude/agents/revisor.md\nname: revisor\ndescription: revisa PRs"],
      highlight_text: "",
      variant: "",
      cover_variant: "dark_speaker",
      headline_style: "clean",
      cover_image_prompt: "",
      bg_image_url: "",
      cta_text: "",
    },
    {
      index: 4,
      type: "tip",
      eyebrow: "FECHAMENTO",
      title: "Dica de quem já quebrou a cara",
      body: "Comece com um agente só, bem descrito. Vários agentes genéricos brigam entre si e o resultado piora.",
      bullet_points: [],
      highlight_text: "",
      variant: "",
      cover_variant: "dark_speaker",
      headline_style: "clean",
      cover_image_prompt: "",
      bg_image_url: "",
      cta_text: "",
    },
    {
      index: 5,
      type: "cta",
      eyebrow: "",
      title: "Quer o tutorial escrito, com tudo copiável?",
      body: "Mando o passo a passo completo no seu Direct, com os comandos prontos.",
      bullet_points: [],
      highlight_text: "AGENTE",
      variant: "",
      cover_variant: "dark_speaker",
      headline_style: "clean",
      cover_image_prompt: "",
      bg_image_url: "",
      cta_text: "",
    },
  ],
};

const prompt: InstagramCarouselContent = {
  title: "Prompt — exemplo de carrossel",
  edition_date: "2026-01-01",
  primary_topic: "Estética GTA VI",
  target_audience_focus: "Criadores, Vendedores & Empreendedores",
  format: "prompt",
  caption: CAPTION_STUB,
  slides: [
    {
      index: 1,
      type: "cover",
      eyebrow: "",
      title: "Sua foto na estética de GTA VI",
      body: "",
      bullet_points: [],
      highlight_text: "",
      variant: "",
      cover_variant: "dark_speaker",
      headline_style: "clean",
      cover_image_prompt: "",
      bg_image_url: "",
      cta_text: "",
    },
    {
      index: 2,
      type: "gallery",
      eyebrow: "",
      title: "o mesmo conceito — casal",
      body: "",
      bullet_points: [],
      highlight_text: "",
      variant: "",
      cover_variant: "dark_speaker",
      headline_style: "clean",
      cover_image_prompt: "",
      bg_image_url: "",
      cta_text: "",
    },
    {
      index: 3,
      type: "gallery",
      eyebrow: "",
      title: "seu pet vira personagem",
      body: "",
      bullet_points: [],
      highlight_text: "",
      variant: "",
      cover_variant: "dark_speaker",
      headline_style: "clean",
      cover_image_prompt: "",
      bg_image_url: "",
      cta_text: "",
    },
  ],
};

export const SAMPLE_CAROUSEL: Record<CarouselFormat, InstagramCarouselContent> = {
  noticia,
  tutorial,
  prompt,
};
