import type { NewsSourceConfig } from "./news-sources";

/**
 * Fontes de oportunidade nos EUA, para o canal social.
 *
 * A medição de capacidade mostrou que o gargalo do Instagram não é o filtro
 * editorial: é a oferta. Das 29 fontes em uso, quase todas são consultas do
 * Google News sobre imigração, e a imigração noticiada é majoritariamente
 * restritiva. Num dia medido, 15 pautas de relevância 8, todas dos EUA, todas
 * de imigração, e 12 delas classificadas como desfavoráveis: a linha editorial
 * remove justamente o que é mais relevante, e o que sobra é notícia doméstica
 * brasileira.
 *
 * A correção certa é ampliar a oferta, não baixar a régua. Estas fontes
 * cobrem o que faltava: mercado de trabalho, expansão de empresa, investimento
 * que aterrissa, agência estadual de desenvolvimento econômico, pesquisa e
 * demanda por profissional. É onde a notícia positiva sobre os EUA nasce.
 *
 * Todas foram testadas duas vezes, por processos independentes: HTTP 200,
 * corpo de feed válido, ao menos três itens e item mais recente de 2026.
 *
 * As generalistas (universidade, imprensa setorial) entram com `keywords`,
 * porque sem filtro elas afogam o pool com o que não é pauta daqui.
 *
 * Esta lista é a SEMENTE. O pipeline lê `project_news_sources` no banco.
 */
export const fontesDeOportunidade: Array<NewsSourceConfig & { eixo: string; porQue: string }> = [
  {
    id: "indeed-hiring-lab",
    name: "Indeed Hiring Lab",
    type: "rss",
    url: "https://www.hiringlab.org/feed/",
    enabled: true,
    priority: 2,
    category: "research",
    region: "global",
    keywords: [],
    eixo: "trabalho-economia",
    porQue: "Centro de pesquisa do Indeed sobre mercado de trabalho americano: relatorio mensal de empregos, JOLTS, ranking de melhores cidades para trabalhar e analise setorial de vagas, com dado bruto de contrat",
  },
  {
    id: "liberty-street-economics-fed-de-nova-york",
    name: "Liberty Street Economics (Fed de Nova York)",
    type: "rss",
    url: "https://libertystreeteconomics.newyorkfed.org/feed/",
    enabled: true,
    priority: 2,
    category: "research",
    region: "global",
    keywords: ["labor", "job", "wage", "employment", "hiring", "productivity", "growth", "immigra"],
    eixo: "trabalho-economia",
    porQue: "Blog de pesquisa economica do Federal Reserve de Nova York, com analise de produtividade, mercado de trabalho e efeito da IA sobre empregos, quase sempre em tom de expansao e transformacao produtiva.",
  },
  {
    id: "bureau-of-economic-analysis-bea",
    name: "Bureau of Economic Analysis (BEA)",
    type: "rss",
    url: "https://apps.bea.gov/rss/rss.xml",
    enabled: true,
    priority: 1,
    category: "gov_us",
    region: "global",
    keywords: [],
    eixo: "trabalho-economia",
    porQue: "Fonte primaria oficial do PIB americano, renda pessoal, gastos das familias e comercio exterior; entrega o numero duro de crescimento e de renda que ancora pauta positiva sobre a economia dos EUA.",
  },
  {
    id: "census-bureau-indicadores-economicos",
    name: "Census Bureau - Indicadores Economicos",
    type: "rss",
    url: "https://www.census.gov/economic-indicators/indicator.xml",
    enabled: true,
    priority: 1,
    category: "gov_us",
    region: "global",
    keywords: [],
    eixo: "trabalho-economia",
    porQue: "Sala de indicadores economicos do Census: construcao, industria, comercio e formacao de negocios, com calendario oficial de divulgacao. Base para pauta de expansao setorial e abertura de empresas.",
  },
  {
    id: "dallas-fed-atualizacoes-economicas",
    name: "Dallas Fed - Atualizacoes Economicas",
    type: "rss",
    url: "https://www.dallasfed.org/rss/updates.xml",
    enabled: true,
    priority: 1,
    category: "gov_us",
    region: "global",
    keywords: ["economic indicators", "employment", "beige book", "jobs", "labor", "growth"],
    eixo: "trabalho-economia",
    porQue: "Indicadores economicos regionais do Texas por metropole (Houston, Austin, Dallas) mais o Weekly Economic Index. Cobre exatamente os destinos de maior fluxo brasileiro, com dado de emprego e cresciment",
  },
  {
    id: "atlanta-fed-gdpnow",
    name: "Atlanta Fed - GDPNow",
    type: "rss",
    url: "https://www.atlantafed.org/rss/GDPNow",
    enabled: true,
    priority: 1,
    category: "gov_us",
    region: "global",
    keywords: [],
    eixo: "trabalho-economia",
    porQue: "Estimativa em tempo real do crescimento do PIB americano, atualizada varias vezes por mes. Cada item ja vem com o numero no titulo, o que rende manchete direta de economia americana acelerando.",
  },
  {
    id: "dallas-fed-comunicados",
    name: "Dallas Fed - Comunicados",
    type: "rss",
    url: "https://www.dallasfed.org/rss/releases.xml",
    enabled: true,
    priority: 1,
    category: "gov_us",
    region: "global",
    keywords: ["economic indicators", "employment", "beige book", "jobs", "labor", "growth"],
    eixo: "trabalho-economia",
    porQue: "Newsroom oficial do Fed de Dallas, incluindo o Beige Book do Onze Distrito com leitura de condicoes economicas e contratacao no Texas e regiao. Traz tambem nomeacoes, entao exige filtro por assunto.",
  },
  {
    id: "atlanta-fed-wage-growth-tracker",
    name: "Atlanta Fed - Wage Growth Tracker",
    type: "rss",
    url: "https://www.atlantafed.org/rss/WageGrowthTracker",
    enabled: true,
    priority: 1,
    category: "gov_us",
    region: "global",
    keywords: [],
    eixo: "trabalho-economia",
    porQue: "Medidor oficial de crescimento salarial do trabalhador americano. Cada item traz o percentual no titulo, ideal para pauta de salario subindo nos EUA. Atencao: cadencia caiu, ultimo item e de junho de ",
  },
  {
    id: "uscis-alerts-avisos-processuais",
    name: "USCIS Alerts (avisos processuais)",
    type: "rss",
    url: "https://www.uscis.gov/news/rss-feed/22984",
    enabled: true,
    priority: 1,
    category: "gov_us",
    region: "global",
    keywords: [],
    eixo: "imigracao-util",
    porQue: "Fonte primária número um do eixo: nova edição de formulário com data de corte, guia de evidência, abertura de escritório, cap de H-1B atingido e mudança de política de filing, tudo em linguagem de pra",
  },
  {
    id: "federal-register-atos-da-uscis",
    name: "Federal Register, atos da USCIS",
    type: "rss",
    url: "https://www.federalregister.gov/api/v1/documents.rss?conditions%5Bagencies%5D%5B%5D=u-s-citizenship-and-immigration-services",
    enabled: true,
    priority: 1,
    category: "gov_us",
    region: "global",
    keywords: ["visa", "immigration", "H-1B", "employment", "USCIS", "green card", "labor certification", "nonimmigrant"],
    eixo: "imigracao-util",
    porQue: "Diário oficial americano filtrado só na USCIS. Precisão máxima, zero ruído: toda regra, taxa e revisão de formulário da agência aparece aqui antes de virar notícia. Volume baixo porque a janela padrão",
  },
  {
    id: "federal-register-termo-imigrao",
    name: "Federal Register, termo imigração",
    type: "rss",
    url: "https://www.federalregister.gov/api/v1/documents.rss?conditions%5Bterm%5D=immigration",
    enabled: true,
    priority: 1,
    category: "gov_us",
    region: "global",
    keywords: ["visa", "immigration", "H-1B", "employment", "USCIS", "green card", "labor certification", "nonimmigrant"],
    eixo: "imigracao-util",
    porQue: "Rede ampla sobre o diário oficial, pega regra de taxa de H-1B, revisão de formulário e mudança regulatória de qualquer órgão. Atenção: tem ruído fora de tema (aviação, CDL de carga perigosa), então pr",
  },
  {
    id: "bal-berry-appleman-leiden",
    name: "BAL, Berry Appleman & Leiden",
    type: "rss",
    url: "https://www.bal.com/feed/",
    enabled: true,
    priority: 2,
    category: "us_media",
    region: "global",
    keywords: [],
    eixo: "imigracao-util",
    porQue: "O melhor encaixe editorial da lista. Banca de imigração corporativa com pauta de talento e mobilidade: FAQ de tempo de processamento de PERM, contratação global, expansão de empresa. Tom de oportunida",
  },
  {
    id: "murthy-law-firm",
    name: "Murthy Law Firm",
    type: "rss",
    url: "https://www.murthy.com/feed/",
    enabled: true,
    priority: 2,
    category: "us_media",
    region: "global",
    keywords: [],
    eixo: "imigracao-util",
    porQue: "Formato de pergunta e resposta sobre situação concreta de quem está no processo: status de F-1, I-94, autorização de trabalho de cônjuge H-4. É exatamente a dúvida prática de quem planeja a mudança.",
  },
  {
    id: "klasko-immigration-law-partners",
    name: "Klasko Immigration Law Partners",
    type: "rss",
    url: "https://www.klaskolaw.com/feed/",
    enabled: true,
    priority: 2,
    category: "us_media",
    region: "global",
    keywords: [],
    eixo: "imigracao-util",
    porQue: "Análise processual voltada a empregador e investidor: taxa nova de H-1B, período de carência de 60 dias, efeito de advance parole. Explica o que muda no procedimento e o que fazer a respeito.",
  },
  {
    id: "siskind-susser-visalaw-com",
    name: "Siskind Susser, visalaw.com",
    type: "rss",
    url: "https://www.visalaw.com/feed/",
    enabled: true,
    priority: 2,
    category: "us_media",
    region: "global",
    keywords: [],
    eixo: "imigracao-util",
    porQue: "Boletim mensal consolidado de imigração mais resumo de novidades globais, bom para pauta de panorama e de calendário. Cadência é irregular (mensal ou menos), então serve como complemento, não como fon",
  },
  {
    id: "area-development-anncios-de-projetos",
    name: "Area Development - Anúncios de Projetos",
    type: "rss",
    url: "https://www.areadevelopment.com/rss/newsitems.xml",
    enabled: true,
    priority: 2,
    category: "us_media",
    region: "global",
    keywords: [],
    eixo: "negocios-expansao",
    porQue: "É o feed mais direto do eixo: cada item é um anúncio real de nova fábrica, sede ou expansão de operação, com empresa, cidade e estado no título, o que rende pauta de vaga e oportunidade sem nenhum vié",
  },
  {
    id: "site-selection-magazine",
    name: "Site Selection Magazine",
    type: "rss",
    url: "https://siteselection.com/feed/",
    enabled: true,
    priority: 2,
    category: "us_media",
    region: "global",
    keywords: [],
    eixo: "negocios-expansao",
    porQue: "Revista de referência em site selection: explica por que empresas escolhem um estado ou cidade americana, com pautas de polo emergente, custo e clima de negócios estado a estado.",
  },
  {
    id: "manufacturing-dive",
    name: "Manufacturing Dive",
    type: "rss",
    url: "https://www.manufacturingdive.com/feeds/news/",
    enabled: true,
    priority: 2,
    category: "us_media",
    region: "global",
    keywords: ["plant", "jobs", "hiring", "expansion", "investment", "factory", "facility"],
    eixo: "negocios-expansao",
    porQue: "Cobre reshoring, novas plantas e criação de emprego industrial nos EUA, com números de investimento e de vagas prontos para virar pauta positiva.",
  },
  {
    id: "construction-dive",
    name: "Construction Dive",
    type: "rss",
    url: "https://www.constructiondive.com/feeds/news/",
    enabled: true,
    priority: 2,
    category: "us_media",
    region: "global",
    keywords: ["hiring", "jobs", "workforce", "expansion", "project", "investment", "labor"],
    eixo: "negocios-expansao",
    porQue: "Traz obra de infraestrutura, construção de data center e, sobretudo, falta de mão de obra qualificada no canteiro americano, gancho forte para quem pensa em migrar com ofício técnico.",
  },
  {
    id: "utility-dive",
    name: "Utility Dive",
    type: "rss",
    url: "https://www.utilitydive.com/feeds/news/",
    enabled: true,
    priority: 2,
    category: "us_media",
    region: "global",
    keywords: ["investment", "jobs", "plant", "expansion", "construction", "data center"],
    eixo: "negocios-expansao",
    porQue: "Cobre a corrida de energia puxada por data center e hyperscaler, incluindo nuclear modular e novos projetos de geração, que é a maior onda de capex privado em curso nos EUA.",
  },
  {
    id: "department-of-energy-newsroom",
    name: "Department of Energy - Newsroom",
    type: "rss",
    url: "https://www.energy.gov/rss/newsroom.xml",
    enabled: true,
    priority: 1,
    category: "gov_us",
    region: "global",
    keywords: ["investment", "jobs", "plant", "project", "manufacturing", "construction"],
    eixo: "negocios-expansao",
    porQue: "Newsroom oficial com anúncio de capital privado, programas para pequena empresa e expansão de geração, tom institucional otimista sobre a economia e o trabalhador americano.",
  },
  {
    id: "selectflorida-agncia-de-desenvolvimento-econmico",
    name: "SelectFlorida (agência de desenvolvimento econômico da Flórida)",
    type: "rss",
    url: "https://www.selectflorida.org/feed/",
    enabled: true,
    priority: 1,
    category: "gov_us",
    region: "global",
    keywords: [],
    eixo: "estados-cidades",
    porQue: "Anuncia missões internacionais de negócios, parcerias de investimento estrangeiro e expansão de setores como aeroespacial e manufatura avançada na Flórida, estado com forte presença brasileira.",
  },
  {
    id: "texas-edc-corporao-de-desenvolvimento-econmico-d",
    name: "Texas EDC (corporação de desenvolvimento econômico do Texas)",
    type: "rss",
    url: "https://businessintexas.com/feed/",
    enabled: true,
    priority: 1,
    category: "gov_us",
    region: "global",
    keywords: [],
    eixo: "estados-cidades",
    porQue: "Braço oficial de atração de investimento do Texas: setores em alta, incentivos fiscais novos, crédito de P&D e chegada de empresas ao estado.",
  },
  {
    id: "go-biz-califrnia-governor-s-office-of-business-a",
    name: "GO-Biz Califórnia (Governor's Office of Business and Economic Development)",
    type: "rss",
    url: "https://business.ca.gov/feed/",
    enabled: true,
    priority: 1,
    category: "gov_us",
    region: "global",
    keywords: [],
    eixo: "estados-cidades",
    porQue: "Escritório estadual oficial: anúncios de investimento privado bilionário, criação de empregos por setor, produtividade da força de trabalho e captação de investimento estrangeiro.",
  },
  {
    id: "edpnc-economic-development-partnership-of-north-",
    name: "EDPNC (Economic Development Partnership of North Carolina)",
    type: "rss",
    url: "https://edpnc.com/feed/",
    enabled: true,
    priority: 1,
    category: "gov_us",
    region: "global",
    keywords: [],
    eixo: "estados-cidades",
    porQue: "Pauta pura de empresa que chega e vaga que abre: expansões com número de empregos, boom de defesa e semicondutores, novas escolas técnicas e universitárias na Carolina do Norte.",
  },
  {
    id: "tnecd-tennessee-department-of-economic-and-commu",
    name: "TNECD (Tennessee Department of Economic and Community Development)",
    type: "rss",
    url: "https://tnecd.com/news/feed/",
    enabled: true,
    priority: 1,
    category: "gov_us",
    region: "global",
    keywords: [],
    eixo: "estados-cidades",
    porQue: "Secretaria estadual que publica quase diariamente expansão de manufatura com contagem de empregos em cidades pequenas do Tennessee, custo de vida baixo e mercado de trabalho aquecido.",
  },
  {
    id: "go-utah-governor-s-office-of-economic-opportunit",
    name: "Go Utah (Governor's Office of Economic Opportunity)",
    type: "rss",
    url: "https://business.utah.gov/feed/",
    enabled: true,
    priority: 1,
    category: "gov_us",
    region: "global",
    keywords: [],
    eixo: "estados-cidades",
    porQue: "Escritório estadual de Utah: empresas de IA e tecnologia, crédito para pequeno negócio e missões comerciais internacionais, num dos estados de crescimento mais rápido dos EUA.",
  },
  {
    id: "wedc-wisconsin-economic-development-corporation",
    name: "WEDC (Wisconsin Economic Development Corporation)",
    type: "rss",
    url: "https://wedc.org/feed/",
    enabled: true,
    priority: 1,
    category: "gov_us",
    region: "global",
    keywords: [],
    eixo: "estados-cidades",
    porQue: "Corporação estadual do Wisconsin com expansões industriais nomeadas por cidade, investimento em infraestrutura de energia e revitalização de centros urbanos.",
  },
  {
    id: "missouri-partnership-agncia-de-atrao-de-investim",
    name: "Missouri Partnership (agência de atração de investimento do Missouri)",
    type: "rss",
    url: "https://www.missouripartnership.com/feed/",
    enabled: true,
    priority: 1,
    category: "gov_us",
    region: "global",
    keywords: [],
    eixo: "estados-cidades",
    porQue: "Foco quase exclusivo em empresa estrangeira que escolhe o Missouri para a primeira fábrica nos EUA e em terrenos industriais certificados, ou seja, investimento que aterrissa.",
  },
  {
    id: "nsf-news-national-science-foundation",
    name: "NSF News (National Science Foundation)",
    type: "rss",
    url: "https://www.nsf.gov/rss/rss_www_news.xml",
    enabled: true,
    priority: 1,
    category: "gov_us",
    region: "global",
    keywords: [],
    eixo: "educacao-profissoes",
    porQue: "Anúncios oficiais de investimento bilionário em centros de pesquisa e institutos americanos, pauta naturalmente positiva sobre a capacidade científica dos EUA e sobre onde há dinheiro e vaga para pesq",
  },
  {
    id: "ncses-estatsticas-de-cincia-e-engenharia-da-nsf",
    name: "NCSES (estatísticas de ciência e engenharia da NSF)",
    type: "rss",
    url: "https://ncses.nsf.gov/rss",
    enabled: true,
    priority: 1,
    category: "gov_us",
    region: "global",
    keywords: [],
    eixo: "educacao-profissoes",
    porQue: "Fonte primária dos números oficiais de força de trabalho em ciência e engenharia, doutorados, estudantes internacionais e gasto em P&D, o dado bruto que sustenta matéria sobre demanda por profissional",
  },
  {
    id: "iie-institute-of-international-education",
    name: "IIE (Institute of International Education)",
    type: "rss",
    url: "https://www.iie.org/feed/",
    enabled: true,
    priority: 2,
    category: "research",
    region: "global",
    keywords: [],
    eixo: "educacao-profissoes",
    porQue: "A organização que administra o Fulbright e publica o Open Doors, referência mundial em mobilidade acadêmica. Pauta de bolsa, intercâmbio e caminho de carreira internacional, exatamente o ângulo de opo",
  },
  {
    id: "mit-news",
    name: "MIT News",
    type: "rss",
    url: "https://news.mit.edu/rss/feed",
    enabled: true,
    priority: 2,
    category: "research",
    region: "global",
    keywords: ["research", "hiring", "startup", "jobs", "engineer", "career", "international", "graduate", "fellowship", "scholarship"],
    eixo: "educacao-profissoes",
    porQue: "Newsroom oficial de alto volume e altíssima densidade de descoberta científica e perfil de pesquisador estrangeiro, o retrato mais forte dos EUA como destino de talento técnico.",
  },
  {
    id: "harvard-gazette",
    name: "Harvard Gazette",
    type: "rss",
    url: "https://news.harvard.edu/gazette/feed/",
    enabled: true,
    priority: 2,
    category: "research",
    region: "global",
    keywords: ["research", "economy", "jobs", "immigration", "international", "graduate", "career", "fellowship"],
    eixo: "educacao-profissoes",
    porQue: "Newsroom oficial com 50 itens e atualização diária, cobre pesquisa, programa acadêmico e nomeação. Volume alto compensa o fato de parte da pauta ser crítica e cair no filtro.",
  },
  {
    id: "berkeley-news-uc-berkeley",
    name: "Berkeley News (UC Berkeley)",
    type: "rss",
    url: "https://news.berkeley.edu/feed/",
    enabled: true,
    priority: 2,
    category: "research",
    region: "global",
    keywords: ["research", "economy", "jobs", "immigration", "international", "graduate", "career"],
    eixo: "educacao-profissoes",
    porQue: "Universidade pública de ponta na Califórnia, publica muita história de ascensão de aluno de origem humilde e imigrante, o arco narrativo de oportunidade que a linha editorial pede.",
  },
  {
    id: "georgia-tech-news",
    name: "Georgia Tech News",
    type: "rss",
    url: "https://news.gatech.edu/rss.xml",
    enabled: true,
    priority: 2,
    category: "research",
    region: "global",
    keywords: ["research", "hiring", "jobs", "engineer", "career", "international", "graduate"],
    eixo: "educacao-profissoes",
    porQue: "Newsroom de engenharia e computação com forte ligação com indústria, boa para pauta de formação técnica e absorção de engenheiro pelo mercado americano.",
  },
  {
    id: "ieee-spectrum",
    name: "IEEE Spectrum",
    type: "rss",
    url: "https://spectrum.ieee.org/feeds/feed.rss",
    enabled: true,
    priority: 2,
    category: "tech_media",
    region: "global",
    keywords: ["jobs", "hiring", "career", "engineer shortage", "workforce", "salary"],
    eixo: "educacao-profissoes",
    porQue: "Publicação da maior associação profissional de engenharia do mundo, cobre carreira, mentoria, formação e avanço técnico, o recorte de demanda por engenheiro e profissional de tecnologia.",
  },
];
