export type NewsSourceType = "rss" | "atom" | "html" | "api";

export type NewsSourceConfig = {
  id: string;
  name: string;
  companyName?: string;
  type: NewsSourceType;
  url: string;
  enabled: boolean;
  priority: 1 | 2;
  category: "lab" | "tech_media" | "research" | "general_ai" | "br_media";
  region?: "global" | "br";
};

export const defaultNewsSources: NewsSourceConfig[] = [
  // Prioridade 1: Laboratórios e Empresas de IA Oficiais Globais
  {
    id: "openai-blog",
    name: "OpenAI Official Blog",
    companyName: "OpenAI",
    type: "rss",
    url: "https://openai.com/news/rss.xml",
    enabled: true,
    priority: 1,
    category: "lab",
    region: "global",
  },
  {
    id: "anthropic-news",
    name: "Anthropic News & Research",
    companyName: "Anthropic",
    type: "rss",
    url: "https://www.anthropic.com/feed.xml",
    enabled: true,
    priority: 1,
    category: "lab",
    region: "global",
  },
  {
    id: "google-deepmind",
    name: "Google DeepMind Blog",
    companyName: "Google",
    type: "rss",
    url: "https://deepmind.google/blog/rss.xml",
    enabled: true,
    priority: 1,
    category: "lab",
    region: "global",
  },
  {
    id: "meta-ai-blog",
    name: "Meta AI Blog",
    companyName: "Meta",
    type: "rss",
    url: "https://ai.meta.com/blog/rss/",
    enabled: true,
    priority: 1,
    category: "lab",
    region: "global",
  },
  {
    id: "microsoft-ai-blog",
    name: "Microsoft Official AI Blog",
    companyName: "Microsoft",
    type: "rss",
    url: "https://blogs.microsoft.com/ai/feed/",
    enabled: true,
    priority: 1,
    category: "lab",
    region: "global",
  },
  {
    id: "huggingface-blog",
    name: "Hugging Face Blog",
    companyName: "Hugging Face",
    type: "rss",
    url: "https://huggingface.co/blog/feed.xml",
    enabled: true,
    priority: 1,
    category: "lab",
    region: "global",
  },
  {
    id: "github-blog-ai",
    name: "GitHub AI Blog",
    companyName: "GitHub",
    type: "rss",
    url: "https://github.blog/category/ai/feed/",
    enabled: true,
    priority: 1,
    category: "lab",
    region: "global",
  },
  {
    id: "aws-ai-blog",
    name: "AWS Machine Learning Blog",
    companyName: "Amazon",
    type: "rss",
    url: "https://aws.amazon.com/blogs/machine-learning/feed/",
    enabled: true,
    priority: 1,
    category: "lab",
    region: "global",
  },

  // Fontes do Brasil (Prioridade 1 & 2 - Tecnologia, IA e Inovação BR)
  {
    id: "canaltech-rss",
    name: "Canaltech (Tecnologia & IA BR)",
    type: "rss",
    url: "https://canaltech.com.br/rss/",
    enabled: true,
    priority: 1,
    category: "br_media",
    region: "br",
  },
  {
    id: "tecnoblog-rss",
    name: "Tecnoblog",
    type: "rss",
    url: "https://tecnoblog.net/feed/",
    enabled: true,
    priority: 1,
    category: "br_media",
    region: "br",
  },
  {
    id: "manual-do-usuario",
    name: "Manual do Usuário",
    type: "rss",
    url: "https://manualdousuario.net/feed/",
    enabled: true,
    priority: 1,
    category: "br_media",
    region: "br",
  },
  {
    id: "startse-feed",
    name: "StartSe Inovação & IA",
    type: "rss",
    url: "https://www.startse.com/feed/",
    enabled: true,
    priority: 2,
    category: "br_media",
    region: "br",
  },
  {
    id: "baguete-diario",
    name: "Baguete Diário de TI",
    type: "rss",
    url: "https://www.baguete.com.br/feed",
    enabled: true,
    priority: 2,
    category: "br_media",
    region: "br",
  },
  {
    id: "ti-inside",
    name: "TI Inside Brasil",
    type: "rss",
    url: "https://tiinside.com.br/feed/",
    enabled: true,
    priority: 2,
    category: "br_media",
    region: "br",
  },

  // Mídia Internacional de Tecnologia
  {
    id: "techcrunch-ai",
    name: "TechCrunch AI",
    type: "rss",
    url: "https://techcrunch.com/category/artificial-intelligence/feed/",
    enabled: true,
    priority: 2,
    category: "tech_media",
    region: "global",
  },
  {
    id: "arstechnica-ai",
    name: "Ars Technica AI",
    type: "rss",
    url: "https://feeds.arstechnica.com/arstechnica/technology-lab",
    enabled: true,
    priority: 2,
    category: "tech_media",
    region: "global",
  },
  {
    id: "venturebeat-ai",
    name: "VentureBeat AI",
    type: "rss",
    url: "https://venturebeat.com/category/ai/feed/",
    enabled: true,
    priority: 2,
    category: "tech_media",
    region: "global",
  },
  {
    id: "mit-tech-review",
    name: "MIT Technology Review AI",
    type: "rss",
    url: "https://www.technologyreview.com/topic/artificial-intelligence/feed",
    enabled: true,
    priority: 2,
    category: "tech_media",
    region: "global",
  },
  {
    id: "theverge-ai",
    name: "The Verge AI",
    type: "rss",
    url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
    enabled: true,
    priority: 2,
    category: "tech_media",
    region: "global",
  },
];
